---
- hosts: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: prep system
      include: tasks/prep.yml

    - name: Install packages.
      include: tasks/packages.yml